--------------------------------------------------------------------------------
-- <auto-generated>                                                           --
--     This code was generated by a tool.                                     --
--                                                                            --
--     Changes to this file may cause incorrect behavior and will be lost if  --
--     the code is regenerated.                                               --
-- </auto-generated>                                                          --
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--                                                                            --
--    Copyright(c) 2018 Alexander Gamper, All Rights Reserved.                --
--                                                                            --
--    Ada-WinRT                                                               --
--                                                                            --
-- This program is free software: you can redistribute it and / or modify     --
-- it under the terms of the GNU Lesser General Public License as published by--
-- the Free Software Foundation, either version 3 of the License, or          --
-- (at your option) any later version.                                        --
--                                                                            --
-- This program is distributed in the hope that it will be useful,            --
-- but WITHOUT ANY WARRANTY; without even the implied warranty of             --
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               --
-- GNU Lesser General Public License for more details.                        --
--                                                                            --
-- You should have received a copy of the GNU Lesser General Public License   --
-- along with this program.If not, see http://www.gnu.org/licenses            --
--                                                                            --
--------------------------------------------------------------------------------
with Windows.System;
with Windows.UI;
with Windows.UI.Composition;
with Ada.Unchecked_Conversion;
--------------------------------------------------------------------------------
package body Windows.UI.WindowManagement is

   ------------------------------------------------------------------------
   -- Delegates/Events
   ------------------------------------------------------------------------
   
   function Invoke
   (
      This       : access AsyncOperationCompletedHandler_IAppWindow_Interface
      ; asyncInfo : Windows.UI.WindowManagement.IAsyncOperation_IAppWindow
      ; asyncStatus : Windows.Foundation.AsyncStatus
   )
   return Windows.HRESULT is
      Hr : Windows.HRESULT := S_OK;
   begin
      This.Callback(asyncInfo, asyncStatus);
      return Hr;
   end;
   
   function Invoke
   (
      This       : access TypedEventHandler_IAppWindow_add_Changed_Interface
      ; sender : Windows.UI.WindowManagement.IAppWindow
      ; args : Windows.UI.WindowManagement.IAppWindowChangedEventArgs
   )
   return Windows.HRESULT is
      Hr : Windows.HRESULT := S_OK;
   begin
      This.Callback(Windows.UI.WindowManagement.IAppWindow(sender), Windows.UI.WindowManagement.IAppWindowChangedEventArgs(args));
      return Hr;
   end;
   
   function Invoke
   (
      This       : access TypedEventHandler_IAppWindow_add_Closed_Interface
      ; sender : Windows.UI.WindowManagement.IAppWindow
      ; args : Windows.UI.WindowManagement.IAppWindowClosedEventArgs
   )
   return Windows.HRESULT is
      Hr : Windows.HRESULT := S_OK;
   begin
      This.Callback(Windows.UI.WindowManagement.IAppWindow(sender), Windows.UI.WindowManagement.IAppWindowClosedEventArgs(args));
      return Hr;
   end;
   
   function Invoke
   (
      This       : access TypedEventHandler_IAppWindow_add_CloseRequested_Interface
      ; sender : Windows.UI.WindowManagement.IAppWindow
      ; args : Windows.UI.WindowManagement.IAppWindowCloseRequestedEventArgs
   )
   return Windows.HRESULT is
      Hr : Windows.HRESULT := S_OK;
   begin
      This.Callback(Windows.UI.WindowManagement.IAppWindow(sender), Windows.UI.WindowManagement.IAppWindowCloseRequestedEventArgs(args));
      return Hr;
   end;
   
   function Invoke
   (
      This       : access TypedEventHandler_IDisplayRegion_add_Changed_Interface
      ; sender : Windows.UI.WindowManagement.IDisplayRegion
      ; args : Windows.Object
   )
   return Windows.HRESULT is
      Hr : Windows.HRESULT := S_OK;
   begin
      This.Callback(Windows.UI.WindowManagement.IDisplayRegion(sender), args);
      return Hr;
   end;
   
   function Invoke
   (
      This       : access TypedEventHandler_IWindowingEnvironment_add_Changed_Interface
      ; sender : Windows.UI.WindowManagement.IWindowingEnvironment
      ; args : Windows.UI.WindowManagement.IWindowingEnvironmentChangedEventArgs
   )
   return Windows.HRESULT is
      Hr : Windows.HRESULT := S_OK;
   begin
      This.Callback(Windows.UI.WindowManagement.IWindowingEnvironment(sender), Windows.UI.WindowManagement.IWindowingEnvironmentChangedEventArgs(args));
      return Hr;
   end;
   
   ------------------------------------------------------------------------
   -- Create functions (for activatable classes)
   ------------------------------------------------------------------------
   
   function Create return Windows.UI.WindowManagement.ICompactOverlayPresentationConfiguration is
      Hr            : Windows.HResult := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.CompactOverlayPresentationConfiguration");
      Instance      : aliased IInspectable := null;
      RefCount      : Windows.UInt32 := 0;
      RetVal        : aliased IUnknown := null;
      function Convert is new Ada.Unchecked_Conversion(IUnknown , Windows.UI.WindowManagement.ICompactOverlayPresentationConfiguration) with inline;
   begin
      Hr := RoActivateInstance(m_hString, Instance'Address);
      if Hr = 0 then
         Hr := Instance.QueryInterface(Windows.UI.WindowManagement.IID_ICompactOverlayPresentationConfiguration'Access, RetVal'access);
         RefCount := Instance.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
      return Convert(RetVal);
   end;
   
   function Create return Windows.UI.WindowManagement.IDefaultPresentationConfiguration is
      Hr            : Windows.HResult := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.DefaultPresentationConfiguration");
      Instance      : aliased IInspectable := null;
      RefCount      : Windows.UInt32 := 0;
      RetVal        : aliased IUnknown := null;
      function Convert is new Ada.Unchecked_Conversion(IUnknown , Windows.UI.WindowManagement.IDefaultPresentationConfiguration) with inline;
   begin
      Hr := RoActivateInstance(m_hString, Instance'Address);
      if Hr = 0 then
         Hr := Instance.QueryInterface(Windows.UI.WindowManagement.IID_IDefaultPresentationConfiguration'Access, RetVal'access);
         RefCount := Instance.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
      return Convert(RetVal);
   end;
   
   function Create return Windows.UI.WindowManagement.IFullScreenPresentationConfiguration is
      Hr            : Windows.HResult := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.FullScreenPresentationConfiguration");
      Instance      : aliased IInspectable := null;
      RefCount      : Windows.UInt32 := 0;
      RetVal        : aliased IUnknown := null;
      function Convert is new Ada.Unchecked_Conversion(IUnknown , Windows.UI.WindowManagement.IFullScreenPresentationConfiguration) with inline;
   begin
      Hr := RoActivateInstance(m_hString, Instance'Address);
      if Hr = 0 then
         Hr := Instance.QueryInterface(Windows.UI.WindowManagement.IID_IFullScreenPresentationConfiguration'Access, RetVal'access);
         RefCount := Instance.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
      return Convert(RetVal);
   end;
   
   ------------------------------------------------------------------------
   -- Override Implementations
   ------------------------------------------------------------------------
   
   ------------------------------------------------------------------------
   -- Static procedures/functions
   ------------------------------------------------------------------------
   
   procedure ClearAllPersistedState
   is
      Hr            : Windows.HRESULT := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.AppWindow");
      m_Factory     : IAppWindowStatics := null;
      RefCount      : Windows.UInt32 := 0;
   begin
      Hr := RoGetActivationFactory(m_hString, IID_IAppWindowStatics'Access , m_Factory'Address);
      if Hr = 0 then
         Hr := m_Factory.ClearAllPersistedState;
         RefCount := m_Factory.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
   end;
   
   procedure ClearPersistedState
   (
      key : Windows.String
   )
   is
      Hr            : Windows.HRESULT := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.AppWindow");
      m_Factory     : IAppWindowStatics := null;
      RefCount      : Windows.UInt32 := 0;
   begin
      Hr := RoGetActivationFactory(m_hString, IID_IAppWindowStatics'Access , m_Factory'Address);
      if Hr = 0 then
         Hr := m_Factory.ClearPersistedState(key);
         RefCount := m_Factory.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
   end;
   
   function TryCreateAsync
   return Windows.UI.WindowManagement.IAsyncOperation_IAppWindow is
      Hr            : Windows.HRESULT := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.AppWindow");
      m_Factory     : IAppWindowStatics := null;
      RefCount      : Windows.UInt32 := 0;
      RetVal        : aliased Windows.UI.WindowManagement.IAsyncOperation_IAppWindow;
   begin
      Hr := RoGetActivationFactory(m_hString, IID_IAppWindowStatics'Access , m_Factory'Address);
      if Hr = 0 then
         Hr := m_Factory.TryCreateAsync(RetVal'Access);
         RefCount := m_Factory.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
      return RetVal;
   end;
   
   function FindAll
   return Windows.UI.WindowManagement.IVectorView_IWindowingEnvironment is
      Hr            : Windows.HRESULT := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.WindowingEnvironment");
      m_Factory     : IWindowingEnvironmentStatics := null;
      RefCount      : Windows.UInt32 := 0;
      RetVal        : aliased Windows.UI.WindowManagement.IVectorView_IWindowingEnvironment;
   begin
      Hr := RoGetActivationFactory(m_hString, IID_IWindowingEnvironmentStatics'Access , m_Factory'Address);
      if Hr = 0 then
         Hr := m_Factory.FindAll(RetVal'Access);
         RefCount := m_Factory.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
      return RetVal;
   end;
   
   function FindAllWithKind
   (
      kind : Windows.UI.WindowManagement.WindowingEnvironmentKind
   )
   return Windows.UI.WindowManagement.IVectorView_IWindowingEnvironment is
      Hr            : Windows.HRESULT := S_OK;
      m_hString     : Windows.String := To_String("Windows.UI.WindowManagement.WindowingEnvironment");
      m_Factory     : IWindowingEnvironmentStatics := null;
      RefCount      : Windows.UInt32 := 0;
      RetVal        : aliased Windows.UI.WindowManagement.IVectorView_IWindowingEnvironment;
   begin
      Hr := RoGetActivationFactory(m_hString, IID_IWindowingEnvironmentStatics'Access , m_Factory'Address);
      if Hr = 0 then
         Hr := m_Factory.FindAllWithKind(kind, RetVal'Access);
         RefCount := m_Factory.Release;
      end if;
      Hr := WindowsDeleteString(m_hString);
      return RetVal;
   end;
   
end;
